version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:18 # Use a Node.js Docker image (adjust version as needed)
    steps:
      - run: 
          name: cd into backend
          command: cd /backend
      - run: # Install dependencies
          name: Install Dependencies
          command: npm install
      - run: # Run tests
          name: Run Jest Tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
