version: 2.1
orbs:
  # See the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2
jobs:
  test:
    steps:
      - run: 
          name: cd into backend
          command: cd /backend
      - run: # Install dependencies
          name: Install Dependencies
          command: npm install
      - run: # Run tests
          name: Run Jest Tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
